TW-299: Metadata rework
madfish-solutions/tezos-metadata-api pull request #31
Opened 2023-05-04 00:15 UTC by alex-tsx

https://madfish.atlassian.net/browse/TW-299

2023-05-04 18:14 UTC, keshan3262 commented on src/index.js
> +  if (!rpcUrl) return;
```suggestion
  if (!rpcUrl) {
    return undefined;
  }
```
Looks more explicit to me

2023-05-04 18:14 UTC, keshan3262 commented on src/tezos.js
> +const buildTezos = (rpcUrl) => {
I think this method should be memoized to avoid the same steps for each metadata query for, for example, mainnet tokens

2023-05-04 18:14 UTC, keshan3262 commented on src/metadata.js
> +  if (chainId === ChainIds.ITHACANET || chainId === ChainIds.ITHACANET2) return 'ghostnet';
```suggestion
  switch (chainId) {
    case ChainIds.MAINNET:
      return 'mainnet';
    case ChainIds.ITHACANET: case ChainIds.ITHACANET2:
      return 'ghostnet';
    default:
      return undefined;
  }
```

2023-05-04 18:14 UTC, keshan3262 commented on src/fixtures.js
> +};
It would be nice to add a final newline

2023-05-05 07:40 UTC, keshan3262 approved these changes

2023-05-09 07:48 UTC, lourenc requested changes
I'd suggest having a short call and discussing the direction of this, as it's a breaking change for many of the services we have

2023-05-09 07:48 UTC, lourenc commented on package.json
> +    "mem": "^8.1.1",
We already have a `memoizee` library inside the project with similar functionality

2023-05-09 07:48 UTC, lourenc commented on src/image-cache.js
> +      return uri.slice(0, 100);
What is the point of returning part of the SVG? It might be better to have nothing returned than a broken image...

2023-05-10 16:21 UTC, lourenc requested changes

2023-05-10 16:23 UTC, lourenc requested changes

2023-05-10 16:23 UTC, lourenc commented on .DS_Store
Please, remove the `.DS_Store` file

2023-05-12 12:58 UTC, lourenc approved these changes
GJ, thnx 👍

2023-05-26 08:34 UTC, keshan3262 commented on src/tzkt.js
> +module.exports = fetchTokenMetadataFromTzkt;
```suggestion
module.exports = fetchTokenMetadataFromTzkt;

```

2023-05-26 08:42 UTC, lourenc requested changes
One minor comment

2023-05-26 08:42 UTC, lourenc commented on src/tzkt.js
> +async function fetchGet(chainId, endpoint, params) {
The naming of this function is slightly unclear, should we call it `fetchFromTzkt(...)` or something like that?

2023-05-26 08:50 UTC, lourenc approved these changes

2023-05-26 08:50 UTC, lourenc approved these changes

2023-05-26 14:30 UTC, merged